SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES*PRICE)
FROM 
    BOOK_SALES S
    ,BOOK B
    ,AUTHOR A
WHERE 
    S.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
    AND (YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1)
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC