SELECT YEAR(SALES_DATE) AS YEAR,
MONTH(SALES_DATE) AS MONTH, USER_INFO.GENDER,
COUNT(DISTINCT USER_INFO.USER_ID) AS USERS
FROM ONLINE_SALE
JOIN USER_INFO
ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID AND 
GENDER IS NOT NULL
GROUP BY YEAR, MONTH, USER_INFO.GENDER
ORDER BY YEAR, MONTH, USER_INFO.GENDER