# ----SELECT FROM JOIN WHERE GROUPBY HAVING ORDERBY 순서----
SELECT USED_GOODS_USER.USER_ID AS USER_ID, 
USED_GOODS_USER.NICKNAME AS NICKNAME,
SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER ON B.WRITER_ID = USED_GOODS_USER.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY USED_GOODS_USER.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES